[database]
name = "Testdb"
user = "postgres"
password = "myadmin"
host = "127.0.0.1"
port = 5432

[image_validation]
image_size = 1145728
image_format = [".jpg", ".png",".jpeg"]
image_size_error = "Please upload an image file smaller than 1MB."
image_format_error = "Please upload a JPG or PNG image."
image_empty_error = "Image not exists, please upload one image..!"