# Generated by Django 4.2 on 2023-05-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='binary_image',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
